### ISSUE TITLE
OpenTTD (ingame) can only show readme.txt, which no longer exists

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenGFX#22]
We converted the `readme.txt` (rightfully) to `README.md`, but OpenTTD ingame can only show `readme.txt` currently.

@ympenguin wrote a script that converts markdown to txt (https://github.com/OpenTTD/OpenGFX/pull/8/commits/6696adce38346099ed250111ac293340bd87b8db), but I am not sure that is the direction we want to go to.

Do we simply want to rename `README.md` to `readme.txt` in the tarball we upload to BaNaNaS? Or convert it as best we can? Opinions?

**Comment by glx22** [comment]
If a `readme.txt` is really required, a rename should be enough I think. Markdown is easily readable by human.
