### ISSUE TITLE
Release 0.5.6 (or 0.6)?

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenGFX#36]
A release of OpenGFX would be good ahead of OpenTTD 1.10

* all the missing sprites are now done as far as I am aware
* we now have a clean build
* as I understand it we can now distribute OpenGFX artefacts again via the website

I don't know how OpenGFX is released (I did check readme and previous issues/PRs for diligence).  

Ideally release process would be documented to reduce bus factor, even if it's as simple as 'tag and push'. :)

**Comment by andythenorth** [comment]
'How to release discussion'

planetmaker	yes, OpenGFX definitely gets a changelog
TrueBrain	andythenorth: it might not be unexpected to you, but you can just tag in the OpenGFX repo, and it does its thing
TrueBrain	the file ends up on the CDN .. and indeed, uploading to BaNaNaS is still manual

**Comment by andythenorth** [comment]
Instructions I will add to readme.

At March 2020, process is:
* update the changelog manually, example https://cdn.openttd.org/opengfx-nightlies/20200226-master-ge4e14d16d7/changelog.txt
* tag + push
* tag will be built and published to CDN
* bananas upload is manual

**Comment by TrueBrain** [comment]
Don't tag+push, go to Releases, Draft new release, and fill in the blanks :)
