### ISSUE TITLE
nmlc ERROR: Image file "sprites/png/infrastructure/locks_normal.gimp.png": cannot identify image file

### ISSUE THREAD

**Issue by Mailaender** [OpenTTD/OpenGFX#47]
I noticed failing builds in @openSUSE so I updated the version (seems we didn't notice the release tarball location switch) however when I compile 0.6 it also fails:
```
[  275s] [CPP] ogfxe_extra.nml
[  275s] [NML] ogfxe_extra.grf
[  276s]  nmlc ERROR: Image file "sprites/png/infrastructure/locks_normal.gimp.png": cannot identify image file '/home/abuild/rpmbuild/BUILD/OpenGFX-0.6.0/sprites/png/infrastructure/locks_normal.gimp.png'
```

**Comment by LordAro** [comment]
Odd, the image is definitely there - https://github.com/OpenTTD/OpenGFX/blob/master/sprites/png/infrastructure/locks_normal.gimp.png
Can you make sure your checkout/tarball contains that file?

**Comment by Mailaender** [comment]
The problem disappears when I remove `make clean-gfx`.

**Comment by LordAro** [comment]
Ah right, yes. This deletes the "generated" files from the source GIMP xcf files. Working as intended.

**Comment by Mailaender** [comment]
Alright. I then removed the broken GIMP path which also decreases build time: https://build.opensuse.org/request/show/859731
