### ISSUE TITLE
Toy factory "hammer" sometimes disconnects

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenGFX#51]
OpenGFX 0.6.0, OpenTTD 1.9.3. Zoom 2×.

Sometimes, the toy factory "hammer" gets disconnected like so:

https://satoshiupload.com/images/osLk6aUaRB.png

I have no idea if this is an OpenGFX or an OpenTTD bug.

**Comment by nielsmh** [comment]
![image](https://user-images.githubusercontent.com/1062071/107095307-d6efd100-6808-11eb-92a2-05415be9d7f3.png)

**Comment by Andrew350** [comment]
As I said in my reply to the other issue (which seemingly got overlooked), it is simply a case of incorrect offsets in OpenGFX. Shifting the buildings to their correct locations will fix this problem and the animation disappearing early. I just haven't got around to making a PR for it yet, but it really is a 2 second fix 🙂
