### ISSUE TITLE
Make readme/changelog/license button clickable.

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenGFX#6]
If you select OpenGFX in the game settings, the buttons for the readme, changelog and license are grayed out.

Can you please make them clickable?

I am using OpenSFX 0.5.5.

**Comment by Wuzzy2** [comment]
Oops! I meant to say:

“I am using OpenGFX 0.5.5.”.

**Comment by TrueBrain** [comment]
Did you use the OpenGFX from BaNaNaS? As that is working for me.

For a while, building your own tarball from source was broken, but that is fixed now too with #24.

Going to close this for now, as I expect this is fixed. If not, please do re-open and let us know where you got the tarball from. Tnx!
