### ISSUE TITLE
Building from github doesn't work

### ISSUE THREAD

**Issue by ympenguin** [OpenTTD/OpenGFX#7]
Building fresh from github without an hg clone doesn't work. As far as I can tell, this is due to a few reasons:
- Makefile.vcs requires the hg tool and the hg repo info
- docs/readme.txt and -.ptxt were removed but are still required by the Makefile.
- Makefile.gfx is not included. This doesn't break the build process, but causes all PNG files to be regenerated and that causes all of them to diff from the repo.
- There's no .gitignore. Again, this doesn't break the build process.

This might all be due to my confusion about where dev is taking place. The website says it has moved to github. The readme still refers to the hg repo, and the hg repo and github are not in sync. If that is the case, please clarify.

**Comment by TrueBrain** [comment]
I think I fixed most of these issues now. The only one I didn't is `Makefile.gfx`, as that strictly seen is not a bug. It is just the way it is implemented in Makefile that is a bit annoying. But that is for future changes :)
