### ISSUE TITLE
Update / add NRT sprites

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenGFX#9]
![ogfx_build_tram](https://user-images.githubusercontent.com/1780327/74975703-65fcb100-541f-11ea-8b66-0a51c2698182.png)

**Comment by frosch123** [comment]
4 sprites by supermop:
http://devs.openttd.org/~frosch/ConvertRoad.png

**Comment by andythenorth** [comment]
Also needs https://github.com/OpenTTD/OpenTTD/blob/master/media/extra_grf/tramtracks_bare_depot.png

[9:26pm] frosch123: it "just" needs copying of the sprites, and overdrawing of the tracks with blue pixels. nothing fancy, just work

**Comment by andythenorth** [comment]
Done
